#!/bin/bash
# 	command << token
# 		command input fr the command input.
# 	token
#
# 	Use <<- instead of << to ignore the spaces/tabs.

cat "This is my_script  \n" 
name="ShekharGH" 
$name

	
cat << _EOF_

<HTML>
<HEAD>
    <TITLE>
    The title of your page
    </TITLE>
</HEAD>

<BODY>
Your page content goes here.
</BODY>
</HTML>
_EOF_
